#pragma once

#define SUCCESS 1
#define FAILED 0
#define FILE_OPENIBG_FAILED -1
#define MEOMORY_ALLOCATION_FAILUER -2
#define KEY_NOT_EXIST -3
#define KEY_HAS_BEEN_DELETED -4
#define ERROR_EXECUTING_SUBFUNCTION -5
#define OVERDUE_KEY -6;